component: payment
service_type: ClusterIP
targetPort: 8080
PARAMETERS: "payment.prod.carthost,CART_HOST payment.prod.cartport,CART_PORT payment.prod.userhost,USER_HOST payment.prod.userport,USER_PORT payment.prod.amqphost,AMQP_HOST payment.prod.amqpuser,AMQP_USER payment.prod.amqppass,AMQP_PASS"
env: prod
schema:
  enabled: false